global:
  scrape_interval: 15s
scrape_configs:
  - job_name: "cadvisor"
    static_configs:
      - targets:
          - cadvisor:8080
  - job_name: node
    static_configs:
      - targets:
          - node-exporter:9100
  - job_name: "jaeger-metrics"
    metrics_path: /metrics
    static_configs:
      - targets: ["jaeger:14269"]
  - job_name: "Microservices metrics"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 3s
    static_configs:
      - targets:
          [
            "host.docker.internal:8081",
            "host.docker.internal:8082",
            "host.docker.internal:8080",
          ]
        labels:
          application: "Microservices Spring Boot Application"
