name: Accommodation Project
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven
      - name: Build model
        uses: actions/checkout@v3
        with:
          repository: av-devops2024/model
          token: ${{ secrets.PAT_TOKEN }}
          run: mvn install
      - name: Build Accommodation
        run: mvn -B validate sonar:sonar -Dsonar.projectKey=$PROJECT_KEY -Dsonar.organization=accommodation
        env:
          SONAR_TOKEN: ${{ secrets.SONNAR_TOKEN }}
