name: Accommodation Project
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - develop
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONNAR_TOKEN }}
        run: mvn validate sonar:sonar \
          -Dsonar.organization=accommodation \
          -Dsonar.projectKey=$PROJECT_KEY
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven
      - name: Build model
        project: av-devops2024/model
        build-command: mvn install
      - name: Build with Maven cloud
        run: mvn -B verify sonar:sonar -Dsonar.projectKey=$PROJECT_KEY -Dsonar.organization=accommodation
        env:
          SONAR_TOKEN: ${{ secrets.SONNAR_TOKEN }}
