name: Accommodation Project
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SONAR_TOKEN: ${{ secrets.SONNAR_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven
      - name: Build model
        uses: actions/checkout@v2
        with:
          repository: av-devops2024/model
          token: ${{ secrets.PAT_TOKEN }}
          path: model-repo
          run: mvn install

      - name: Start Spring Boot application
        uses: actions/checkout@v2
        with:
          repository: av-devops2024/notifications
          ref: develop
          token: ${{ secrets.PAT_TOKEN }}
          run: |
            mvn spring-boot:run &
            sleep 60  # Wait for the application to start

      - name: Switch back to Accommodation
        uses: actions/checkout@v2
        with:
          repository: av-devops2024/accommodation
          token: ${{ secrets.PAT_TOKEN }}
          run: mvn -B validate sonar:sonar -Dsonar.projectKey=$PROJECT_KEY -Dsonar.organization=accommodation

      - name: Stop Spring Boot application
        uses: actions/checkout@v2
        with:
          repository: av-devops2024/notification
          ref: develop
          token: ${{ secrets.PAT_TOKEN }}
          run: |
            pkill -f 'java.*spring-boot'
