name: Accommodation Project
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Cache Model Maven repository
        uses: actions/cache@v4
        with:
          repository: av-devops2024/model
          path: ~/.m2/repository
          key: model-${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            model-${{ runner.os }}-maven-
      
      - name: Add Model
        uses: actions/checkout@v4
        with:
          repository: av-devops2024/model
          ref: develop
          token: ${{ secrets.PAT_TOKEN }}
          path: model-repo

      - name: Build Model
        run: |
          cd model-repo
          mvn clean install

      - name: Cache Notifications Maven repository
        uses: actions/cache@v4
        with:
          repository: av-devops2024/notifications
          path: ~/.m2/repository
          key: notifications-${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            notifications-${{ runner.os }}-maven-
            
      - name: Build notifications
        uses: actions/checkout@v2
        with:
          repository: av-devops2024/notifications
          token: ${{ secrets.PAT_TOKEN }}
          run: mvn clean install
      - name: Start Spring Boot application
        uses: actions/checkout@v2
        with:
          repository: av-devops2024/notifications
          ref: develop
          token: ${{ secrets.PAT_TOKEN }}
          run: |
            mvn spring-boot:run &
            sleep 60  # Wait for the application to start

      - name: Cache Accommodation Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: acc-${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            acc-${{ runner.os }}-maven-

      - name: Build Accommodation with Maven
        uses: actions/checkout@v2
        with:
          repository: av-devops2024/accommodation
          token: ${{ secrets.PAT_TOKEN }}
          run: mvn -B clean verify

      - name: Add Accommodation
        uses: actions/checkout@v2
        with:
          repository: av-devops2024/accommodation
          token: ${{ secrets.PAT_TOKEN }}
          run: mvn -B validate sonar:sonar -Dsonar.projectKey=$PROJECT_KEY -Dsonar.organization=accommodation

      - name: Stop Spring Boot application
        uses: actions/checkout@v2
        with:
          repository: av-devops2024/notifications
          ref: develop
          token: ${{ secrets.PAT_TOKEN }}
          run: |
            pkill -f 'java.*spring-boot'
