name: Accommodation Project
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven
      - name: Build model
        uses: actions/checkout@v3
        with:
          repository: av-devops2024/model
          token: ${{ secrets.PAT_TOKEN }}
          path: model-repo
          run: mvn install
      - name: Build notification
        uses: actions/checkout@v3
        with:
          repository: av-devops2024/notification
          token: ${{ secrets.PAT_TOKEN }}
          path: notification-repo
          run: mvn install
      - name: Build with Maven
        run: mvn clean install
      - name: Start Spring Boot application
        run: |
          mvn spring-boot:run &
          sleep 60  # Wait for the application to start

      - name: Switch back to Accommodation
        with:
          repository: av-devops2024/accommodation
          token: ${{ secrets.PAT_TOKEN }}
          run: mvn -B validate sonar:sonar -Dsonar.projectKey=$PROJECT_KEY -Dsonar.organization=accommodation
          env:
            SONAR_TOKEN: ${{ secrets.SONNAR_TOKEN }}

      - name: Stop Spring Boot application
        with:
          repository: av-devops2024/notification
          token: ${{ secrets.PAT_TOKEN }}
          run: |
            pkill -f 'java.*spring-boot'
