#NAME
name: Build And Push Images to Dockerhub
#EVENT
on:
  push:
    tags:
      - "v*"
#JOBS
jobs:
  build_docker_images:
    name: Build Docker Image To Dockerhub
    runs-on: [ubuntu-latest]
    env:
      GITHUB_PAT: ${{ secrets.PAT_TOKEN }}
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: "17"

      - name: List directory contents
        run: |
          echo "Listing root folder contents:"
          ls -la

      - name: Build Accommodation with Maven
        uses: actions/checkout@v2
        with:
          repository: av-devops2024/accommodation
          token: ${{ secrets.PAT_TOKEN }}
          run: mvn clean install

      - name: Build Docker image
        run: docker build -t acc-image .

      - name: Extract Metadata
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: |
            ${{secrets.DOCKERHUB_USERNAME}}/devops2024-accommodation
          tags: |
            type=semver,pattern={{version}}

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
          logout: true

      - name: Push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}

      # - name: Build And Push
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: .
      #     push: true
      #     tags: ${{ steps.meta.outputs.tags }}
